name: Publish Sample
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  GPR_KEY: ${{ secrets.GPR_KEY }}
  LUCRA_SDK_API_URL: ${{ secrets.LUCRA_SDK_API_URL }}
  LUCRA_SDK_API_KEY: ${{ secrets.LUCRA_SDK_API_KEY }}

jobs:
  release-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Set up Fastlane
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: example

      - name: Set up Firebase authentication
        run: |
          FIREBASE_SERVICE_CREDENTIALS_FILE="${{ runner.temp }}/firebase-service-account.json"
          echo "FIREBASE_SERVICE_CREDENTIALS_FILE=$FIREBASE_SERVICE_CREDENTIALS_FILE" >> $GITHUB_ENV
          set +x # Disable logging secrets
          cat <<EOF > "$FIREBASE_SERVICE_CREDENTIALS_FILE"
          ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          EOF
          set -x # Re-enable logging

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Finalize Android SDK
        run: |
          /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('example/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Release example for Android
        env:
          JAVA_OPTS: '-XX:MaxHeapSize=6g'
        run: |
          yarn run release:android

  release-ios:
    runs-on: self-hosted
    env:
      APP_STORE_CONNECT_API_KEY_ID: ${{secrets.APP_STORE_CONNECT_API_KEY_ID}}
      APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID}}
      APP_STORE_CONNECT_API_KEY_CONTENT: ${{secrets.APP_STORE_CONNECT_API_KEY_CONTENT}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Cache cocoapods
        id: cocoapods-cache
        uses: actions/cache@v4
        with:
          path: |
            **/ios/Pods
          key: ${{ runner.os }}-cocoapods-${{ hashFiles('example/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapods-

      - name: Set up Fastlane
        run: |
          cd example
          gem install bundler:2.4.7
          bundle install

      - name: Install cocoapods
        run: |
          gem install cocoapods

      - name: Validate Podfile.lock consistency
        run: |
          if ! cmp -s Podfile.lock Pods/Manifest.lock; then
            cd example/ios
            echo "Podfile.lock is out of sync, requiring pod install"
            rm -rf Pods/
            pod cache clean --all
            echo "pod_install_required=1" >> $GITHUB_ENV
          fi

      - name: Install cocoapods
        if: steps.cocoapods-cache.outputs.cache-hit != 'true' || env.pod_install_required == '1'
        run: |
          pod repo update
          pod install --repo-update
        working-directory: example/ios

      - name: Release example for iOS
        run: |
          yarn run release:ios
